services:
  sftp-standby:
    container_name: sftp-standby
    image: sftp
    build: sftp
    restart: always
    ports:
      - '2223:22'
    volumes:
      - '/Users/kuan-linchiu/Documents/Codes/sftp-HA/sftp/config/users.conf:/etc/sftp/users.conf:rw'
      - '/Users/kuan-linchiu/Documents/Codes/sftp-HA/sftp/data-standby:/home:rw'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1