version: "3.1"

services:
  sftp-standby:
    container_name: sftp-standby
    image: harbor.wistron.com/k8sprdwihwilms/wiles/sftp:0.1
    # build: ./sftp
    restart: always
    ports:
      - '2223:22'
    volumes:
      - ./sftp/data-standby:/home:rw
      - ./sftp/config/users.yaml:/home/admin/admin/users.yaml
    networks:
      sftp-net:
        ipv4_address: 10.5.0.3
  
  sftp-sync:
    container_name: sftp-sync
    image: harbor.wistron.com/k8sprdwihwilms/wiles/filesync:0.2
    # build:
    #   context: ./
    #   dockerfile: ./filesync/Dockerfile
    restart: always
    depends_on:
      - sftp-standby
    volumes:
      - ${PWD}/filesync/config.yaml:/var/run/filesync/filesync/config.yaml
    networks:
      - sftp-net

networks:
  sftp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
