version: "3.1"

services:
  sftp-standby:
    container_name: sftp-standby
    # image: sftp:0.1
    build: ./sftp
    restart: always
    ports:
      - '2223:22'
    volumes:
      - './sftp/data-standby:/home:rw'
      - './sftp/config/users.yaml:/home/admin/admin/users.yaml:rw'
    networks:
      sftp-net:
        ipv4_address: 10.5.0.3
  
  sftp-sync:
    container_name: sftp-sync
    # image: filesync:0.1
    build:
      context: ./
      dockerfile: ./filesync/Dockerfile
    restart: always
    depends_on:
      - sftp-standby
    volumes:
      - ${PWD}/filesync/config.yaml:/var/run/filesync/filesync/config.yaml:rw
    networks:
      - sftp-net

networks:
  sftp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
