version: "3.1"

services:
  sftp-master:
    container_name: sftp-master
    image: harbor.wistron.com/k8sprdwihwilms/wiles/sftp:0.1
    # build: ./sftp
    restart: always
    ports:
      - '2222:22'
    volumes:
      - './sftp/data:/home:rw'
      - './sftp/config/users.yaml:/home/admin/admin/users.yaml'
    networks:
      sftp-net:
        ipv4_address: 10.5.0.5

networks:
  sftp-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

