services:
  sftp-master:
    image: sftp
    build: sftp
    restart: always
    container_name: sftp-master
    ports:
      - '2222:22'
    volumes:
      - '/Users/kuan-linchiu/Documents/Codes/sftp-HA/sftp/config/users.conf:/etc/sftp/users.conf:rw'
      - '/Users/kuan-linchiu/Documents/Codes/sftp-HA/sftp/data:/home:rw'
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2


networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
